#!/bin/bash
# https://devcenter.heroku.com/articles/heroku-postgres-import-export
# run as script/clone_production_db (from www dir)

# first time? link your www directory to heroku app
# heroku git:remote -a <appname>
heroku pg:backups capture
mkdir -p backup
curl -o backup/latest.dump `heroku pg:backups public-url`
