#!/bin/bash
# https://devcenter.heroku.com/articles/heroku-postgres-import-export
# run as script/clone_production_db (from www dir)

# first time? link your www directory to heroku app
# heroku git:remote -a <appname>
heroku pg:backups capture
mkdir -p backup
curl -o www/backup/production_db.dump `heroku pg:backups public-url`
docker-compose down
docker-compose up -d db
docker cp www/backup/production_db.dump join-form_db_1:/pgdata/
docker-compose exec db su postgres -c 'psql -c "SELECT pid, (SELECT pg_terminate_backend(pid)) as killed from pg_stat_activity WHERE datname = '"'"'join_form_development'"'"';"'
docker-compose exec db su postgres -c "psql -c 'drop database join_form_development;'"
docker-compose exec db su postgres -c "psql -c 'create database join_form_development;'"
docker-compose exec db su postgres -c "pg_restore --verbose --clean --no-acl --no-owner -d join_form_development pgdata/production_db.dump"
