#!/bin/bash
# https://devcenter.heroku.com/articles/heroku-postgres-import-export
# run as script/clone_production_db
heroku pg:backups capture
curl -o backup/latest.dump `heroku pg:backups public-url`
pg_restore --verbose --clean --no-acl --no-owner -d join_form_development backup/latest.dump

